apiVersion: v2
name: tuf
description: A framework for securing software update systems - the scaffolding implementation
type: application
version: 0.1.33
appVersion: 0.7.39

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/scaffolding

maintainers:
- name: The Sigstore Authors
  url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: scaffolding-tuf
      image: ghcr.io/sigstore/scaffolding/server:v0.7.39@sha256:b5b67a4249041249b0ad97651ff57e1f3be1468d79a01a919b39f0a1952a3def
