apiVersion: v2
name: ctlog-tiles
description: Tiles-based certificate log (TesseraCT)
type: application
version: 0.1.5
appVersion: v0.1.2
keywords:
  - security
  - certificate transparency
home: https://sigstore.dev
sources:
  - https://github.com/transparency-dev/tesseract
maintainers:
  - name: The Sigstore Authors
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: tesseract-posix
      image: ghcr.io/transparency-dev/tesseract/posix:v0.1.2@sha256:b044edd2388857dfc590381ff526214dfea93c6eeb61f632e58633cac2330935
    - name: tesseract-gcp
      image: ghcr.io/transparency-dev/tesseract/gcp:v0.1.2@sha256:37f1e3fb7f511f8c4bacec43e22fb52fb631f77fadb10de8bbf1560594c96fbe
