apiVersion: v2
name: rekor-tiles
description: Part of the sigstore project, Rekor v2 (Rekor on tiles) is a signature transparency log
type: application
version: 1.1.3
appVersion: "2.2.1"
keywords:
  - security
  - transparency logs
home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor-tiles
maintainers:
  - name: The Sigstore Authors
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: rekor-tiles-gcp
      image: ghcr.io/sigstore/rekor-tiles/gcp:v2.2.1@sha256:17f6584cc8f531083a56d3ff2dd4e03b00c604a6b6f6bc62a5e29c7baea46895
    - name: rekor-tiles-posix
      image: ghcr.io/sigstore/rekor-tiles/posix:v2.2.1@sha256:627422bf9da146d1d9ff4e1c1e8301a1780ab6ad9b32bccff51ecd9f8c820e41
    - name: rekor-tiles-aws
      image: ghcr.io/sigstore/rekor-tiles/aws:v2.2.1@sha256:cd82665772e1aaf50e270806a0179fd21cf87c88eb5245a047efc7c6ef02d216
    - name: rekor-tiles-gcpcloudsql
      image: ghcr.io/sigstore/rekor-tiles/gcpcloudsql:v2.2.1@sha256:cf2cec2cd58c17c2a19c9fea81ef33660d92063935122da0491a30beca6c89b0
