apiVersion: v2
name: rekor-tiles
description: Part of the sigstore project, Rekor v2 (Rekor on tiles) is a signature transparency log
type: application
version: 1.2.0
appVersion: "2.3.0"
keywords:
  - security
  - transparency logs
home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor-tiles
maintainers:
  - name: The Sigstore Authors
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: rekor-tiles-gcp
      image: ghcr.io/sigstore/rekor-tiles/gcp:v2.3.0@sha256:e401cfe033c99ec4ac647f61f51dd1c28d686c227d6c6e250a50a110da3a1559
    - name: rekor-tiles-posix
      image: ghcr.io/sigstore/rekor-tiles/posix:v2.3.0@sha256:a5ceeff41b2468f965f7259685a9553c6dbba6870108ffebfa6584df5ae22504
    - name: rekor-tiles-aws
      image: ghcr.io/sigstore/rekor-tiles/aws:v2.3.0@sha256:f403632566bfda42a7ea3904097be4fd1eff907831ec14a11df7f9550c3e2fbc
    - name: rekor-tiles-gcpcloudsql
      image: ghcr.io/sigstore/rekor-tiles/gcpcloudsql:v2.3.0@sha256:76c8e0f82c15f787e6d358dbf1f00a1e3dc6fbd7719ddec9f56550edd9d22c41
