apiVersion: v2
name: fulcio
description: |
  Fulcio is a free code signing Certificate Authority, built to make short-lived certificates available to anyone.

type: application

version: 2.11.4
appVersion: 1.9.0

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: ctlog
    version: 0.2.69
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: fulcio
      image: ghcr.io/sigstore/fulcio:v1.9.0@sha256:2de0226c5f82008091a4c9de4f7b84b081f2bff1d13530d7f7357a6ba19d3835
    - name: createcerts
      image: ghcr.io/sigstore/scaffolding/createcerts:v0.7.33@sha256:4d64dac937e26251327f91a26e188131fc8e9f75ee49bd698d662a3c1bf0d19c
    - name: curlimages/curl
      image: docker.io/curlimages/curl:8.17.0@sha256:935d9100e9ba842cdb060de42472c7ca90cfe9a7c96e4dacb55e79e560b3ff40
