apiVersion: v2
name: tsa
description: |
  Timestamp Authority issuing RFC3161 signed timestamps.

type: application

version: 2.1.1
appVersion: 2.1.0

keywords:
  - security
  - timestamp

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: tsa
      # crane digest ghcr.io/sigstore/timestamp-server:v2.1.0
      image: ghcr.io/sigstore/timestamp-server:v2.1.0@sha256:8637f0482ed1ecb229b44ebd0afc760f6f57114a4d53c6953cf65c00218896b2
