apiVersion: v2
name: tsa
description: |
  Timestamp Authority issuing RFC3161 signed timestamps.

type: application

version: 2.1.4
appVersion: 2.1.4

keywords:
  - security
  - timestamp

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: tsa
      # crane digest ghcr.io/sigstore/timestamp-server:v2.1.4
      image: ghcr.io/sigstore/timestamp-server:v2.1.0@sha256:72be23a6a1019c895ff34d2294c8074b2235723a37a735ad30ee9464a381f593
