apiVersion: v2
name: tsa
description: |
  Timestamp Authority issuing RFC3161 signed timestamps.

type: application

version: 2.1.0
appVersion: 2.0.5

keywords:
  - security
  - timestamp

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: tsa
      # crane digest ghcr.io/sigstore/timestamp-server:v2.0.5
      image: ghcr.io/sigstore/timestamp-server:v2.0.5@sha256:32b8c10c3cbd1408387df24237d9a5f6be3ad680036b11e18ab0a3fe6aac5e69
