namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
  annotations: {}
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/sigstore-probers/prober:v1.0.1@sha256:d1e914e6d6b92ed4d17ad103db4aae4832a3db4f9933ccbe22506bf1a6a7ac64
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    staging: false
    signingConfig: ""
    trustedRoot: ""
    rekorV2Url: ""
    rekorRequests: []
    fulcioRequests: []
    writeProber: false
    grpcPort: 5554
    disableGrpc: true
    frequency: 10
prometheus:
  port: 8080
tolerations: []
nodeSelector: {}
affinity: {}
