---
secrets:
  rekor:
    create: true
    value: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEEYIqMsfyJKe41facMSJ5rDYb3EPp
      lyR+/rwaUgmWQJrp84A23N9dkBAiU+2wtylPLudqUEnAxTggRmrFMBU9TA==
      -----END PUBLIC KEY-----
  fulcio:
    create: true
    value: |
      -----BEGIN CERTIFICATE-----
      MIIDEzCCAfugAwIBAgIUWumC9bMcYBPm+41o25o6+k0qhNEwDQYJKoZIhvcNAQEL
      BQAwGTEXMBUGA1UEAwwORnVsY2lvIFJvb3QgQ0EwHhcNMjYwODI4MTcwMTE4WhcN
      MzYwODI1MTcwMTE4WjAZMRcwFQYDVQQDDA5GdWxjaW8gUm9vdCBDQTCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBALCeqTyeLy8jY2bqiGtg/Ge6Y5N7Hqed
      09UeylXmWTE5pDcdMPSfCnlsbWWUYgzp9/Acp3XBZIMktF+AMBPi/MbfiZGJ+oNM
      Ox5GceUUh9udJDdVibCFRE6gWrn9rEysnUDrBDDZdASBrpeuQYuQctrgZ7dJ9RrC
      KNyKfzVgDcRfATb6Rzo32kkPHY6hQ3HOViyqdR2wX5Py29puH3IOohyiSSR02soR
      eGdrLDVJ0hlDx73Nawat0+IqaSAwBX1HDV0CBPSqBrll9DvWD5mESTMD/r/BQien
      oonB3aw7sj+qGV9/7Gh+Cww7orNSudG3mGjVsAqqOQE3M6Lz3Hpy3FECAwEAAaNT
      MFEwHQYDVR0OBBYEFLdsBq5XCr7hUBn0vgN3JZZ+qIKVMB8GA1UdIwQYMBaAFLds
      Bq5XCr7hUBn0vgN3JZZ+qIKVMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEL
      BQADggEBAEi4IVw3lpLvkoqWbu93sBjmOsP3rjH+wBN6UbzUc52YiSY9LnUOYbkQ
      aQW3ugci+Ln3h+bsQcQgJo/fEmvexogRptwd7cELq9L79r7Jaxu9sIaQDLDV5Lsc
      4kBSgnlgCnEQLLLpPHz3lLXzuSShkfi40gU0aLfC3AtJ+ea22ZDmdrBdCNRv5Unj
      fytR056bqHMhzEZyky5T9bLfIKRcGkIlx+NU19pL3jcnqUwSpCy4aXKF1HRs4kc9
      qnT/02KBxsQwEPjjg0zKuU3XbJZj8H26DKTMHDelhDNp9DE/JefVh338QDRmS1A5
      nLv0L9EYpgfj3IxNS4Ueav2qgOSt+68=
      -----END CERTIFICATE-----
  ctlog:
    create: true
    value: |
      -----BEGIN PUBLIC KEY-----
      MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEGXBB73StRUPwb6eJj362q6KLkbdQ
      A9kIEihAMauuA/bbyk8QanMjGeDLaSDLqn6rPgfidOyxe9jE4sEAfMN83g==
      -----END PUBLIC KEY-----
  tsa:
    create: true
    value: |
      -----BEGIN CERTIFICATE-----
      MIIC+TCCAeGgAwIBAgIUYIcPQ6LDIi1GSqxpSsM2kLueA6EwDQYJKoZIhvcNAQEL
      BQAwFjEUMBIGA1UEAwwLVFNBIFJvb3QgQ0EwHhcNMjYwODI4MTcwMTE4WhcNMzYw
      ODI1MTcwMTE4WjATMREwDwYDVQQDDAhUU0EgTGVhZjCCASIwDQYJKoZIhvcNAQEB
      BQADggEPADCCAQoCggEBAJguhaYu7SREo95GTJ0ejXBqCk8m82MhcmPXoarfAIP/
      fwx00R9U3egWLOM3BNwRy2nlvC6iyt6ehMAyyvlSoQKflD9NNBFNdEdKUlXq5Nfy
      VqFjR/45p3RFdwYqyelO5lXTDToVf3ML+XV+z6nNASQSmS0LCA6U1U9Wo/Es6dvo
      Jtvioo3NLZW/n6wLuTgwzFZDu8wFRqs8km5LOts/515pMXlx5HQ1ndCYhf37kpgO
      hjE6Ad3hCHg3NF00ptksgl43pTaDjAvosx6aAFv3itMa7eP8aH1kiHEggyRmZ/Iv
      72L2pjFpMpR4DcHtDeQRqkpk7ZxKuPb+SbuOD6Tsiu0CAwEAAaNCMEAwHQYDVR0O
      BBYEFClMdCsgHPJvhiF3OBb/xkB9UZqQMB8GA1UdIwQYMBaAFOMKEbtwz2tnfsSM
      YT9rp4V0XPLzMA0GCSqGSIb3DQEBCwUAA4IBAQCSVNkwMoLTApiVRycchhdAdpGB
      E4yplobd6vPaOI61fr4IEVo6U+BnkfYFAImWhIKjkfm9IOpfSR3CNagin4amrlmQ
      apQl7Xrz3/ljFlLjF2EwoHlzkHJjt0bG3MFeu4o0dfQfAAJodtxkY9oXv59Sv733
      lp3e97LLISj5QogjnGQWdtsch1vgxr/GHSCvlWFH7W8USJOpobp9YGPkBGLEgxLI
      ae+zzYfsd6atFEFWUavw8LzA8g6fZBxiC9dliUOkQC98wTvP325namxSmRNs+VsX
      Hg6WPOOlh/rG4bgiZXyLgdXRkfT134HtY3G5AQmLrHWnlvTr2wq39mGvkEQq
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIDDTCCAfWgAwIBAgIUUnSzYPP4zyQM0p7kblPeABCjHb4wDQYJKoZIhvcNAQEL
      BQAwFjEUMBIGA1UEAwwLVFNBIFJvb3QgQ0EwHhcNMjYwODI4MTcwMTE4WhcNMzYw
      ODI1MTcwMTE4WjAWMRQwEgYDVQQDDAtUU0EgUm9vdCBDQTCCASIwDQYJKoZIhvcN
      AQEBBQADggEPADCCAQoCggEBAPAh+RpYwjLUITKVPxzzAEg5W4jwdPFqS36w4N9I
      T5QM814QvVcXgwoPzPSr/5IVhybp4n+4mpD6PoldFMmOb2ZJj7lPUSKHbkqKrkex
      /q8bpp0vdrtmYpFHqD0Gm2sVGwAgULl97qWUkir0tRJA1clwuL+xfGoR4D3Zd4uI
      RffrdGgUZmUxxWHe9mPOl0RKfbsk5ZvJJHsgNkQvADw205qEs+zMQpIyPFTRg64o
      wgIn9BK15Jfs78y/JjVGQiUpZr8A4ZKmF7uObNMDXoc9Ub40pUFiGEE8vBomxdZ+
      RvO5Mu64tvCohVgt1t1ivWDsepCdAWr1ibab+WVjh6eL+W0CAwEAAaNTMFEwHQYD
      VR0OBBYEFOMKEbtwz2tnfsSMYT9rp4V0XPLzMB8GA1UdIwQYMBaAFOMKEbtwz2tn
      fsSMYT9rp4V0XPLzMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEB
      AFAUW+73JRahKK2EgNJPFjxjTXvo03WMpDEWUwJbK6fTsETFwzru7leAyEqp5ILL
      +UM78WPPERxzFBpEb73L8fy82GQOqdhkJu0BsV8tSo/vFjJRr1iKsG9p8PRxp9dF
      lvC4umWsXDBJiLNFGxsj+P9UXvcssn+OSLyeky18g8+/nnAI89tD+WAreYJUxzW6
      5B9htzejXDi+0kE+m1ZWqcdYkYOzD8igYRvMj44avGDMhPB2TxiInCGNy1LLjReI
      WRJ/H2IKM555GTryZXWR/BRPqmrY4aTvQnXZCmwQg+8CqMk0NTLIroxX0KD6Rxzn
      KQX9JAfFf9X8PsANaMkylGg=
      -----END CERTIFICATE-----

