apiVersion: v2
name: trillian
description: |
  Trillian is a log that stores an accurate, immutable and verifiable history of activity.

type: application

version: 0.3.16
appVersion: 1.7.3

keywords:
  - security
  - pki

home: https://sigstore.dev/
sources:
  - https://github.com/google/trillian
  - https://github.com/sigstore/helm-charts/tree/main/charts/trillian

maintainers:
  - name: The Sigstore Authors
    url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: curl
      image: docker.io/curlimages/curl:8.21.0@sha256:7c12af72ceb38b7432ab85e1a265cff6ae58e06f95539d539b654f2cfa64bb13
    - name: netcat
      image: docker.io/subfuzion/netcat@sha256:7e808e84a631d9c2cd5a04f6a084f925ea388e3127553461536c1248c3333c8a
    - name: db_server
      image: gcr.io/trillian-opensource-ci/db_server:v1.5.3@sha256:2a685a38dd0129cceb646c232d285383f614c7e6fa51ff8f512aef78e4298461
    - name: log_server
      image: ghcr.io/sigstore/scaffolding/trillian_log_server:v1.7.3@sha256:5a878e4e4f03790d2dda4b07a551ff9832128b307447d4156255c73690aa2da3
    - name: log_signer
      image: ghcr.io/sigstore/scaffolding/trillian_log_signer:v1.7.3@sha256:28c5ff40963f83ffdf4e2d9ea1e4e2c877c33cfb0ff068f3daad1c1080aad0ac
    - name: cloud_proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.23.0-alpine@sha256:7cf46b7a0251486351cf7ed18dab04d96f05e26deb19d426e237f390e3baef14
    - name: scaffold_cloud_proxy
      image: ghcr.io/sigstore/scaffolding/cloudsqlproxy:v0.7.37@sha256:2cb6ff4ebe7ae82b4c39e5c2b40365b0e4a47adcc244167c7cd364a6f8a9fdda
    - name: createdb
      image: ghcr.io/sigstore/scaffolding/createdb:v0.7.31@sha256:3cee6c78973b82af6c3c3632bf8d44dafbab1632b3999a7292b170237c5dd5cc
