name: Test Charts

on:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed files
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            charts:
              - 'charts/**'

      - name: Set up Helm
        if: steps.changes.outputs.charts == 'true'
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: 'v3.19.2' # pinned due to v4 incompatibility

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        if: steps.changes.outputs.charts == 'true'
        with:
          python-version: '3.13'
          check-latest: true

      - name: Set up chart-testing
        if: steps.changes.outputs.charts == 'true'
        uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0

      - name: Run chart-testing (lint)
        if: steps.changes.outputs.charts == 'true'
        run: ct lint --config ct.yaml

      - name: "Add NGINX Ingress Repository"
        if: steps.changes.outputs.charts == 'true'
        run: |
          helm repo add ingress-nginx "https://kubernetes.github.io/ingress-nginx"
          helm repo update

      - name: Create KIND Cluster
        if: steps.changes.outputs.charts == 'true'
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0

      - name: Install Ingress Controller
        if: steps.changes.outputs.charts == 'true'
        run: "helm install ingress-nginx/ingress-nginx --generate-name --set controller.service.type='NodePort' --set controller.admissionWebhooks.enabled=false --set controller.progressDeadlineSeconds=30"

      - name: Run chart-testing (install)
        if: steps.changes.outputs.charts == 'true'
        run: ct install --config ct-install.yaml
